name: Basic Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter pub get
    - run: flutter build ipa
    - run: flutter build ios --release --no-codesign
    - run: xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release

    - uses: actions/upload-artifact@v2
      with:
          name: adhoc-ipa
          path: build/ios/ipa/*.ipa
   
